services:
  backend:
    build: ./backend
    container_name: eduquest-backend
    restart: always
    ports:
      - "127.0.0.1:8091:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/eduquest.db
      - SECRET_KEY=eduquest-secret-key-change-me-2026
      - PARENT_PASSWORD=parent123
      - CHILD_PASSWORD=child123
      - TELEGRAM_BOT_TOKEN=8808158107:AAFLW-Z6VPXjxe4OIG_DBoQqvS-Rx-eg9cU
      - TELEGRAM_CHAT_ID=410804594
      - UPLOAD_DIR=/app/data/uploads

  frontend:
    build: ./frontend
    container_name: eduquest-frontend
    restart: always
    ports:
      - "0.0.0.0:8090:80"
    depends_on:
      - backend
